const APPLICATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_SUPERVISOR_REVIEW: 'UNDER_SUPERVISOR_REVIEW',
  UNDER_DEPARTMENT_REVIEW: 'UNDER_DEPARTMENT_REVIEW',
  AWAITING_INFO: 'AWAITING_INFO',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
  CLOSED: 'CLOSED',
});

const ALL_APPLICATION_STATUSES = Object.values(APPLICATION_STATUS);

// Statuses in which an applicant may still edit/delete/attach documents,
// i.e. before it has entered anyone's review queue.
const EDITABLE_STATUSES = [APPLICATION_STATUS.DRAFT];

module.exports = { APPLICATION_STATUS, ALL_APPLICATION_STATUSES, EDITABLE_STATUSES };
